# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: backend
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: backend
# #   template:
# #     metadata:
# #       labels:
# #         app: backend
# #     spec:
# #       containers:
# #         - name: backend
# #           image: workingfullstackapp1-backend:latest
# #           imagePullPolicy: Never
# #           ports:
# #             - containerPort: 5000
# #           env:
# #             - name: MONGO_URI
# #               value: "mongodb-service:27017/fullstackdb"


# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: backend-service
# # spec:
# #   selector:
# #     app: backend
# #   ports:
# #     - port: 5000
# #       targetPort: 5000
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: workingfullstackapp1-backend:latest
#           imagePullPolicy: Never  # Add this line
#           ports:
#             - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
# spec:
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000
#   type: ClusterIP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: workingfullstackapp1-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-service:27017/fullstackdb"  # Updated for correct MongoDB service
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
